### ISSUE TITLE
Complete data update when new symbol is selected

### ISSUE THREAD

**Issue by kkott** [patrickkidd/familydiagram#9]
v.1.0.0b3
MacOS El Capitan v.10.11.6
MacBook Pro, late 2011

When data is added to a person's record, you have to click in a blank area of the diagram before selecting another symbol (to add). Could selecting another symbol complete the data update?

**Comment by patrickkidd** [comment]
See #8. Though it doesn't break the other select/move/delete workflows to show the properties for a new selection if the old properties are already shown.
